// <auto-generated />
using HciMedico.Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HciMedico.Library.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240307130432_TestMigration2")]
    partial class TestMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HciMedico.Library.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TestNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TestName = "Test 1",
                            TestNumber = 123456
                        },
                        new
                        {
                            Id = 2,
                            TestName = "Test 2",
                            TestNumber = 789876
                        },
                        new
                        {
                            Id = 3,
                            TestName = "Test 3",
                            TestNumber = 543212
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
